spring.application.name=forademao

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.datasource.url=jdbc:mysql://localhost:3306/forademao
spring.datasource.username=root
spring.datasource.password=root
